# Site wide configuration

title:            Meren on Microbial Ecology and Bioinformatics
locale:           en_US
url:              //meren.github.io


# Jekyll configuration

permalink: /:year/:month/:day/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Meren
  avatar: bio-photo.jpg
  bio: "I study microbial ecology using my background in computation."
  email: a.murat.eren@gmail.com
  disqus-shortname: merensgithub 
  twitter: merenbey
  facebook: #username
  github: meren
  linkedin: meren

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
