name: anvio-7
channels:
  - bioconda
  - defaults
dependencies:
  - _r-mutex=1.0.0=anacondar_1
  - bioconductor-qvalue=2.16.0=r36_1
  - blast=2.6.0=boost1.64_2
  - bowtie2=2.3.5.1=py36h2dec4b4_0
  - bwa=0.7.17=h2573ce8_7
  - bwidget=1.9.11=1
  - bzip2=1.0.8=h1de35cc_0
  - ca-certificates=2020.12.8=hecd8cb5_0
  - cairo=1.14.12=hc4e6be7_4
  - cctools=927.0.2=h5ba7a2e_4
  - centrifuge=1.0.4_beta=py36pl526ha92aebf_2
  - certifi=2020.12.5=py36hecd8cb5_0
  - clang=10.0.0=default_hf57f61e_0
  - clang_osx-64=10.0.0=h05bbb7f_0
  - clangxx=10.0.0=default_hf57f61e_0
  - clangxx_osx-64=10.0.0=h05bbb7f_1
  - compiler-rt=10.0.0=h47ead80_0
  - compiler-rt_osx-64=10.0.0=hbcc88fd_0
  - curl=7.67.0=ha441bb4_0
  - diamond=0.9.14=hd174df1_3
  - fasttree=2.1.10=h0b31af3_4
  - fontconfig=2.13.0=h5d5b041_1
  - freetype=2.10.4=ha233b18_0
  - fribidi=1.0.10=haf1e3a3_0
  - gettext=0.19.8.1=h15daf44_3
  - gfortran_osx-64=4.8.5=h22b1bf0_8
  - glib=2.63.1=hd977a24_0
  - graphite2=1.3.14=h38d11af_0
  - gsl=2.4=h1de35cc_4
  - harfbuzz=2.4.0=h831d699_0
  - hmmer=3.3.1=h4a8c4bd_0
  - icu=58.2=h0a44026_3
  - infernal=1.1.3=h0b31af3_0
  - iqtree=2.0.3=h7eed37d_0
  - jpeg=9b=he5867d9_2
  - krb5=1.16.4=hddcf347_0
  - ld64=450.3=h3c32e8a_4
  - libcurl=7.67.0=h051b688_0
  - libcxx=10.0.0=1
  - libedit=3.1.20191231=h1de35cc_1
  - libffi=3.2.1=1
  - libgcc=4.8.5=hdbeacc1_10
  - libgfortran=3.0.1=h93005f0_2
  - libiconv=1.16=h1de35cc_0
  - libllvm10=10.0.1=h76017ad_5
  - libopenblas=0.3.10=h0794777_0
  - libpng=1.6.37=ha441bb4_0
  - libssh2=1.9.0=ha12b0ac_1
  - libtiff=4.1.0=hcb84e12_1
  - libxml2=2.9.10=h7cdb67c_3
  - llvm-openmp=10.0.0=h28b9765_0
  - lz4-c=1.9.2=h79c402e_3
  - make=4.2.1=h3efe00b_1
  - mcl=14.137=pl526h01d97ff_5
  - megahit=1.2.9=hfbae3c0_0
  - muscle=3.8.1551=h770b8ee_5
  - ncurses=6.2=h0a44026_1
  - openssl=1.1.1i=h9ed2024_0
  - pango=1.42.4=hc249df1_1
  - pcre=8.44=hb1e8313_0
  - perl=5.26.2=h4e221da_0
  - pip=20.3.3=py36hecd8cb5_0
  - pixman=0.40.0=haf1e3a3_0
  - prodigal=2.6.3=h01d97ff_2
  - python=3.6.10=hfe9666f_1
  - r-askpass=1.0=r36h1de35cc_0
  - r-assertthat=0.2.1=r36h6115d3f_0
  - r-backports=1.1.4=r36h46e59ec_0
  - r-base=3.6.1=hcb44179_1
  - r-base64enc=0.1_3=r36h46e59ec_4
  - r-bh=1.69.0_1=r36h6115d3f_0
  - r-broom=0.5.2=r36h6115d3f_0
  - r-callr=3.2.0=r36h6115d3f_0
  - r-cellranger=1.1.0=r36h6115d3f_0
  - r-cli=1.1.0=r36h6115d3f_0
  - r-clipr=0.6.0=r36h6115d3f_0
  - r-colorspace=1.4_1=r36h46e59ec_0
  - r-crayon=1.3.4=r36h6115d3f_0
  - r-curl=3.3=r36h46e59ec_0
  - r-dbi=1.0.0=r36h6115d3f_0
  - r-dbplyr=1.4.0=r36h6115d3f_0
  - r-dichromat=2.0_0=r36h6115d3f_4
  - r-digest=0.6.18=r36h46e59ec_0
  - r-dplyr=0.8.0.1=r36h466af19_0
  - r-ellipsis=0.1.0=r36h46e59ec_0
  - r-evaluate=0.13=r36h6115d3f_0
  - r-fansi=0.4.0=r36h46e59ec_0
  - r-forcats=0.4.0=r36h6115d3f_0
  - r-fs=1.2.7=r36h466af19_0
  - r-generics=0.0.2=r36h6115d3f_0
  - r-getopt=1.20.3=r36h6115d3f_0
  - r-ggplot2=3.1.1=r36h6115d3f_0
  - r-glue=1.3.1=r36h46e59ec_0
  - r-gtable=0.3.0=r36h6115d3f_0
  - r-haven=2.1.0=r36h466af19_0
  - r-highr=0.8=r36h6115d3f_0
  - r-hms=0.4.2=r36h6115d3f_0
  - r-htmltools=0.3.6=r36h466af19_0
  - r-httr=1.4.0=r36h6115d3f_0
  - r-jsonlite=1.6=r36h46e59ec_0
  - r-knitr=1.22=r36h6115d3f_0
  - r-labeling=0.3=r36h6115d3f_4
  - r-lattice=0.20_38=r36h46e59ec_0
  - r-lazyeval=0.2.2=r36h46e59ec_0
  - r-lubridate=1.7.4=r36h466af19_0
  - r-magrittr=1.5=r36h6115d3f_4
  - r-markdown=0.9=r36h46e59ec_0
  - r-mass=7.3_51.3=r36h46e59ec_0
  - r-matrix=1.2_17=r36h46e59ec_0
  - r-mgcv=1.8_28=r36h46e59ec_0
  - r-mime=0.6=r36h46e59ec_0
  - r-modelr=0.1.4=r36h6115d3f_0
  - r-munsell=0.5.0=r36h6115d3f_0
  - r-nlme=3.1_139=r36hfffe0aa_0
  - r-openssl=1.3=r36h46e59ec_0
  - r-optparse=1.6.2=r36h6115d3f_0
  - r-pillar=1.3.1=r36h6115d3f_0
  - r-pkgconfig=2.0.2=r36h6115d3f_0
  - r-plogr=0.2.0=r36h6115d3f_0
  - r-plyr=1.8.4=r36h466af19_0
  - r-prettyunits=1.0.2=r36h6115d3f_0
  - r-processx=3.3.0=r36h46e59ec_0
  - r-progress=1.2.0=r36h6115d3f_0
  - r-ps=1.3.0=r36h46e59ec_0
  - r-purrr=0.3.2=r36h46e59ec_0
  - r-r6=2.4.0=r36h6115d3f_0
  - r-rcolorbrewer=1.1_2=r36h6115d3f_0
  - r-rcpp=1.0.1=r36h466af19_0
  - r-readr=1.3.1=r36h466af19_0
  - r-readxl=1.3.1=r36h466af19_0
  - r-rematch=1.0.1=r36h6115d3f_0
  - r-reprex=0.2.1=r36h6115d3f_0
  - r-reshape2=1.4.3=r36h466af19_0
  - r-rlang=0.3.4=r36h46e59ec_0
  - r-rmarkdown=1.12=r36h6115d3f_0
  - r-rstudioapi=0.10=r36h6115d3f_0
  - r-rvest=0.3.3=r36h6115d3f_0
  - r-scales=1.0.0=r36h466af19_0
  - r-selectr=0.4_1=r36h6115d3f_0
  - r-stringi=1.4.3=r36h466af19_0
  - r-stringr=1.4.0=r36h6115d3f_0
  - r-sys=3.2=r36h46e59ec_0
  - r-tibble=2.1.1=r36h46e59ec_0
  - r-tidyr=0.8.3=r36h466af19_0
  - r-tidyselect=0.2.5=r36h466af19_0
  - r-tidyverse=1.2.1=r36h6115d3f_0
  - r-tinytex=0.12=r36h6115d3f_0
  - r-utf8=1.1.4=r36h46e59ec_0
  - r-viridislite=0.3.0=r36h6115d3f_0
  - r-whisker=0.3_2=r36h6115d3f_4
  - r-withr=2.1.2=r36h6115d3f_0
  - r-xfun=0.6=r36h6115d3f_0
  - r-xml2=1.2.0=r36h466af19_0
  - r-yaml=2.2.0=r36h46e59ec_0
  - readline=7.0=h1de35cc_5
  - samtools=1.4.1=0
  - setuptools=51.0.0=py36hecd8cb5_2
  - spades=3.12.0=1
  - sqlite=3.33.0=hffcf06c_0
  - tapi=1000.10.8=ha1b3eb9_0
  - tbb=2020.3=h879752b_0
  - tk=8.6.10=hb0a8c7a_0
  - tktable=2.10=h1de35cc_0
  - trimal=1.4.1=ha1b3eb9_4
  - trnascan-se=2.0.7=pl526h0b31af3_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h1de35cc_0
  - zlib=1.2.11=h1de35cc_3
  - zstd=1.4.5=h41d2c2f_0
