name: anvio-7
channels:
  - au-eoed
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - _r-mutex=1.0.1=anacondar_1
  - binutils_impl_linux-64=2.35.1=h193b22a_1
  - binutils_linux-64=2.35=hc3fd857_29
  - bioconductor-qvalue=2.16.0=r36_1
  - blast=2.10.1=pl526he19e7b1_3
  - boost=1.70.0=py36h9de70de_1
  - boost-cpp=1.70.0=ha2d47e9_1
  - bowtie2=2.4.2=py36h5202f60_1
  - bwa=0.7.17=hed695b0_7
  - bwidget=1.9.14=ha770c72_0
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.11.0=h470a237_1
  - ca-certificates=2020.12.5=ha878542_0
  - cairo=1.14.12=h8948797_3
  - centrifuge=1.0.4_beta=py36pl526he941832_2
  - certifi=2020.12.5=py36h5fab9bb_0
  - curl=7.71.1=he644dc0_8
  - diamond=0.9.14=h8b12597_3
  - entrez-direct=13.9=pl526h375a9b1_0
  - expat=2.2.9=he1b5a44_2
  - fastani=1.32=he1c1bb9_0
  - fasttree=2.1.10=h516909a_4
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.10.4=h7ca028e_0
  - fribidi=1.0.10=h36c2ea0_0
  - gcc_impl_linux-64=7.5.0=hda68d29_13
  - gcc_linux-64=7.5.0=he2a3fca_29
  - gettext=0.19.8.1=h0b5b191_1005
  - gfortran_impl_linux-64=7.5.0=hfca37b7_17
  - gfortran_linux-64=7.5.0=ha081f1e_29
  - glib=2.66.4=hcd2ae1e_1
  - graphite2=1.3.13=h58526e2_1001
  - gsl=2.4=h294904e_1006
  - gxx_impl_linux-64=7.5.0=h64c220c_13
  - gxx_linux-64=7.5.0=h547f3ba_29
  - h5py=2.8.0=py36h31fdc65_1005
  - harfbuzz=2.4.0=hca77d97_0
  - hdf5=1.10.4=nompi_h3c11f04_1106
  - hmmer=3.3=he1b5a44_1
  - icu=58.2=hf484d3e_1000
  - infernal=1.1.3=h516909a_0
  - iqtree=2.0.3=h176a8bc_1
  - jpeg=9d=h36c2ea0_0
  - kernel-headers_linux-64=2.6.32=h77966d4_13
  - krb5=1.17.2=h926e7f8_0
  - ld_impl_linux-64=2.35.1=hea4e1c9_1
  - libblas=3.9.0=6_openblas
  - libcblas=3.9.0=6_openblas
  - libcurl=7.71.1=hcdd3856_8
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libffi=3.3=h58526e2_2
  - libgcc=7.2.0=h69d50b8_2
  - libgcc-devel_linux-64=9.3.0=hfd08b2a_17
  - libgcc-ng=9.3.0=h5dbcf3e_17
  - libgfortran-ng=7.5.0=hae1eefd_17
  - libgfortran4=7.5.0=hae1eefd_17
  - libglib=2.66.4=h164308a_1
  - libgomp=9.3.0=h5dbcf3e_17
  - libiconv=1.16=h516909a_0
  - liblapack=3.9.0=6_openblas
  - libnghttp2=1.41.0=hab1572f_1
  - libopenblas=0.3.12=pthreads_hb3c22a3_1
  - libpng=1.6.37=h21135ba_2
  - libssh2=1.9.0=hab1572f_5
  - libstdcxx-devel_linux-64=9.3.0=h4084dd6_17
  - libstdcxx-ng=9.3.0=h2ae2ef3_17
  - libtiff=4.2.0=hdc55705_0
  - libuuid=1.0.3=h1bed415_2
  - libwebp-base=1.1.0=h36c2ea0_3
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.10=hb55368b_3
  - llvm-openmp=8.0.1=hc9558a2_0
  - lz4-c=1.9.3=h9c3ff4c_0
  - make=4.3=hd18ef5c_1
  - mcl=14.137=pl526h516909a_5
  - megahit=1.2.9=h8b12597_0
  - muscle=3.8.1551=hc9558a2_5
  - ncurses=6.2=h58526e2_4
  - numpy=1.19.4=py36h2aa4a07_2
  - openmp=8.0.1=0
  - openssl=1.1.1i=h7f98852_0
  - pandoc=2.11.3.2=h7f98852_0
  - pango=1.45.3=hd140c19_0
  - pcre=8.44=he1b5a44_0
  - pcre2=10.36=h032f7d1_0
  - perl=5.26.2=h36c2ea0_1008
  - perl-app-cpanminus=1.7044=pl526_1
  - perl-archive-tar=2.32=pl526_0
  - perl-base=2.23=pl526_1
  - perl-business-isbn=3.004=pl526_0
  - perl-business-isbn-data=20140910.003=pl526_0
  - perl-carp=1.38=pl526_3
  - perl-common-sense=3.74=pl526_2
  - perl-compress-raw-bzip2=2.087=pl526he1b5a44_0
  - perl-compress-raw-zlib=2.087=pl526hc9558a2_0
  - perl-constant=1.33=pl526_1
  - perl-data-dumper=2.173=pl526_0
  - perl-digest-hmac=1.03=pl526_3
  - perl-digest-md5=2.55=pl526_0
  - perl-encode=2.88=pl526_1
  - perl-encode-locale=1.05=pl526_6
  - perl-exporter=5.72=pl526_1
  - perl-exporter-tiny=1.002001=pl526_0
  - perl-extutils-makemaker=7.36=pl526_1
  - perl-file-listing=6.04=pl526_1
  - perl-file-path=2.16=pl526_0
  - perl-file-temp=0.2304=pl526_2
  - perl-html-parser=3.72=pl526h6bb024c_5
  - perl-html-tagset=3.20=pl526_3
  - perl-html-tree=5.07=pl526_1
  - perl-http-cookies=6.04=pl526_0
  - perl-http-daemon=6.01=pl526_1
  - perl-http-date=6.02=pl526_3
  - perl-http-message=6.18=pl526_0
  - perl-http-negotiate=6.01=pl526_3
  - perl-io-compress=2.087=pl526he1b5a44_0
  - perl-io-html=1.001=pl526_2
  - perl-io-socket-ssl=2.066=pl526_0
  - perl-io-zlib=1.10=pl526_2
  - perl-json=4.02=pl526_0
  - perl-json-xs=2.34=pl526h6bb024c_3
  - perl-libwww-perl=6.39=pl526_0
  - perl-list-moreutils=0.428=pl526_1
  - perl-list-moreutils-xs=0.428=pl526_0
  - perl-lwp-mediatypes=6.04=pl526_0
  - perl-lwp-protocol-https=6.07=pl526_4
  - perl-mime-base64=3.15=pl526_1
  - perl-mozilla-ca=20180117=pl526_1
  - perl-net-http=6.19=pl526_0
  - perl-net-ssleay=1.88=pl526h90d6eec_0
  - perl-ntlm=1.09=pl526_4
  - perl-parent=0.236=pl526_1
  - perl-pathtools=3.75=pl526h14c3975_1
  - perl-scalar-list-utils=1.52=pl526h516909a_0
  - perl-socket=2.027=pl526_1
  - perl-storable=3.15=pl526h14c3975_0
  - perl-test-requiresinternet=0.05=pl526_0
  - perl-time-local=1.28=pl526_1
  - perl-try-tiny=0.30=pl526_1
  - perl-types-serialiser=1.0=pl526_2
  - perl-uri=1.76=pl526_0
  - perl-www-robotrules=6.02=pl526_3
  - perl-xml-namespacesupport=1.12=pl526_0
  - perl-xml-parser=2.44_01=pl526ha1d75be_1002
  - perl-xml-sax=1.02=pl526_0
  - perl-xml-sax-base=1.09=pl526_0
  - perl-xml-sax-expat=0.51=pl526_3
  - perl-xml-simple=2.25=pl526_1
  - perl-xsloader=0.24=pl526_0
  - pip=20.3.3=pyhd8ed1ab_0
  - pixman=0.40.0=h36c2ea0_0
  - prodigal=2.6.3=h516909a_2
  - pthread-stubs=0.4=h36c2ea0_1001
  - python=3.6.12=hffdb5ce_0_cpython
  - python_abi=3.6=1_cp36m
  - r-askpass=1.1=r36hcdcec82_2
  - r-assertthat=0.2.1=r36h6115d3f_2
  - r-backports=1.2.1=r36hcfec24a_0
  - r-base=3.6.1=haffb61f_2
  - r-base64enc=0.1_3=r36hcdcec82_1004
  - r-blob=1.2.1=r36h6115d3f_1
  - r-brio=1.1.0=r36h9e2df91_1
  - r-broom=0.7.3=r36hc72bb7e_0
  - r-callr=3.5.1=r36h142f84f_0
  - r-cellranger=1.1.0=r36h6115d3f_1003
  - r-cli=2.2.0=r36hc72bb7e_0
  - r-clipr=0.7.1=r36h142f84f_0
  - r-colorspace=2.0_0=r36h9e2df91_0
  - r-cpp11=0.2.4=r36hc72bb7e_0
  - r-crayon=1.3.4=r36h6115d3f_1003
  - r-curl=4.3=r36hcdcec82_1
  - r-dbi=1.1.0=r36h6115d3f_1
  - r-dbplyr=2.0.0=r36hc72bb7e_0
  - r-desc=1.2.0=r36h6115d3f_1003
  - r-diffobj=0.3.2=r36h9e2df91_1
  - r-digest=0.6.27=r36h1b71b39_0
  - r-dplyr=1.0.2=r36h0357c0b_0
  - r-ellipsis=0.3.1=r36hcdcec82_0
  - r-evaluate=0.14=r36h6115d3f_2
  - r-fansi=0.4.1=r36hcdcec82_1
  - r-farver=2.0.3=r36h0357c0b_1
  - r-forcats=0.5.0=r36h6115d3f_1
  - r-fs=1.5.0=r36h0357c0b_0
  - r-generics=0.1.0=r36hc72bb7e_0
  - r-getopt=1.20.3=r36_2
  - r-ggplot2=3.3.3=r36hc72bb7e_0
  - r-glue=1.4.2=r36hcdcec82_0
  - r-gtable=0.3.0=r36h6115d3f_3
  - r-haven=2.3.1=r36hde08347_0
  - r-highr=0.8=r36h6115d3f_2
  - r-hms=0.5.3=r36h6115d3f_1
  - r-htmltools=0.5.0=r36h0357c0b_0
  - r-httr=1.4.2=r36h6115d3f_0
  - r-isoband=0.2.3=r36h03ef668_0
  - r-jsonlite=1.7.2=r36hcfec24a_0
  - r-knitr=1.30=r36h6115d3f_0
  - r-labeling=0.4.2=r36h142f84f_0
  - r-lattice=0.20_41=r36hcdcec82_2
  - r-lifecycle=0.2.0=r36h6115d3f_1
  - r-lubridate=1.7.9.2=r36he524a50_0
  - r-magrittr=2.0.1=r36h9e2df91_1
  - r-markdown=1.1=r36hcdcec82_1
  - r-mass=7.3_53=r36hcdcec82_0
  - r-matrix=1.3_0=r36he454529_0
  - r-mgcv=1.8_33=r36h7fa42b6_0
  - r-mime=0.9=r36hcdcec82_1
  - r-modelr=0.1.8=r36h6115d3f_0
  - r-munsell=0.5.0=r36h6115d3f_1003
  - r-nlme=3.1_139=r36ha65eedd_0
  - r-openssl=1.4.3=r36he5c4762_0
  - r-optparse=1.6.6=r36h6115d3f_1
  - r-pillar=1.4.7=r36hc72bb7e_0
  - r-pkgbuild=1.2.0=r36hc72bb7e_0
  - r-pkgconfig=2.0.3=r36h6115d3f_1
  - r-pkgload=1.1.0=r36h0357c0b_0
  - r-plyr=1.8.6=r36h0357c0b_1
  - r-praise=1.0.0=r36h6115d3f_1004
  - r-prettyunits=1.1.1=r36h6115d3f_1
  - r-processx=3.4.5=r36hcfec24a_0
  - r-progress=1.2.2=r36h6115d3f_2
  - r-ps=1.5.0=r36hcfec24a_0
  - r-purrr=0.3.4=r36hcdcec82_1
  - r-r6=2.5.0=r36hc72bb7e_0
  - r-rcolorbrewer=1.1_2=r36h6115d3f_1003
  - r-rcpp=1.0.5=r36he524a50_0
  - r-readr=1.4.0=r36h1b71b39_0
  - r-readxl=1.3.1=r36hde08347_4
  - r-rematch=1.0.1=r36h6115d3f_1003
  - r-rematch2=2.1.2=r36h6115d3f_1
  - r-reprex=0.3.0=r36h6115d3f_2
  - r-reshape2=1.4.4=r36h0357c0b_1
  - r-rlang=0.4.10=r36hcfec24a_0
  - r-rmarkdown=2.6=r36hc72bb7e_0
  - r-rprojroot=2.0.2=r36hc72bb7e_0
  - r-rstudioapi=0.13=r36hc72bb7e_0
  - r-rvest=0.3.6=r36h6115d3f_0
  - r-scales=1.1.1=r36h6115d3f_0
  - r-selectr=0.4_2=r36h6115d3f_1
  - r-stringi=1.4.3=r36h29659fb_0
  - r-stringr=1.4.0=r36h6115d3f_2
  - r-sys=3.4=r36hcdcec82_0
  - r-testthat=3.0.1=r36h03ef668_0
  - r-tibble=3.0.4=r36h0eb13af_0
  - r-tidyr=1.1.2=r36h0357c0b_0
  - r-tidyselect=1.1.0=r36h6115d3f_0
  - r-tidyverse=1.3.0=r36h6115d3f_2
  - r-tinytex=0.28=r36hc72bb7e_0
  - r-utf8=1.1.4=r36hcdcec82_1003
  - r-vctrs=0.3.6=r36hcfec24a_0
  - r-viridislite=0.3.0=r36h6115d3f_1003
  - r-waldo=0.2.3=r36hc72bb7e_0
  - r-whisker=0.4=r36h6115d3f_1
  - r-withr=2.3.0=r36h6115d3f_0
  - r-xfun=0.19=r36h9e2df91_0
  - r-xml2=1.3.2=r36h0357c0b_1
  - r-yaml=2.2.1=r36hcdcec82_1
  - r-zeallot=0.1.0=r36h6115d3f_1002
  - readline=8.0=he28a2e2_2
  - samtools=1.7=1
  - sed=4.8=he412f7d_0
  - setuptools=49.6.0=py36h9880bd3_2
  - six=1.15.0=pyh9f0ad1d_0
  - spades=3.14.1=h2d02072_0
  - sqlite=3.34.0=h74cdb3f_0
  - sysroot_linux-64=2.12=h77966d4_13
  - tbb=2020.2=h4bd325d_2
  - tk=8.6.10=h21135ba_1
  - tktable=2.10=hb7b940f_3
  - trimal=1.4.1=hc9558a2_4
  - trnascan-se=2.0.7=pl526h516909a_0
  - wheel=0.36.2=pyhd3deb0d_0
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libx11=1.6.12=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.5=h516909a_1
  - zlib=1.2.11=h516909a_1010
  - zstd=1.4.8=ha95c52a_1
