name: anvio-6.2
channels:
  - r
  - salilab
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _r-mutex=1.0.1=anacondar_1
  - anvio=6.2=0
  - anvio-minimal=6.2=py_1
  - appdirs=1.4.3=py_1
  - aragorn=1.2.38=2
  - asgiref=3.2.7=py_0
  - attrs=19.3.0=py_0
  - barrnap=0.9=3
  - bedtools=2.29.2=h37cfd92_0
  - bioconductor-qvalue=2.8.0=0
  - biopython=1.76=py36h0b31af3_0
  - blast=2.9.0=pl526hb2f8ae4_4
  - blast-legacy=2.2.26=2
  - boost=1.70.0=py36haf112f3_1
  - boost-cpp=1.70.0=hd59e818_1
  - boost-mac=1.57.0=0
  - bottle=0.12.17=py_0
  - bowtie2=2.3.5=py36h5c9b4e4_0
  - bwa=0.7.17=h2573ce8_7
  - bwidget=1.9.14=0
  - bzip2=1.0.8=h0b31af3_2
  - ca-certificates=2020.4.5.2=hecda079_0
  - cairo=1.16.0=h0ab9d94_1001
  - cctools=895=1
  - cd-hit=4.8.1=hfbae3c0_3
  - centrifuge=1.0.4_beta=py36pl526ha92aebf_2
  - certifi=2020.4.5.2=py36h9f0ad1d_0
  - cffi=1.14.0=py36h356ff06_0
  - chardet=3.0.4=py36h9f0ad1d_1006
  - cheroot=8.3.0=py36h9f0ad1d_1
  - cherrypy=8.0.0=py36_0
  - clang=4.0.1=1
  - clang_osx-64=4.0.1=h1ce6c1d_17
  - clangxx=4.0.1=1
  - clangxx_osx-64=4.0.1=h22b1bf0_17
  - clustalw=2.1=h770b8ee_5
  - colored=1.3.93=py_0
  - compiler-rt=4.0.1=hcfea43d_1
  - configargparse=1.2=pyh9f0ad1d_0
  - cryptography=2.8=py36hc9d8292_2
  - curl=7.68.0=h8754def_0
  - cycler=0.10.0=py_2
  - datrie=0.8.2=py36h37b9a7d_0
  - dbus=1.13.6=h2f22bb5_0
  - decorator=4.4.2=py_0
  - diamond=0.9.14=hd28b015_2
  - django=3.0.5=py36h9f0ad1d_0
  - docutils=0.16=py36h9f0ad1d_1
  - dssp=2.2.1=0
  - entrez-direct=13.3=pl526h375a9b1_0
  - ete3=3.1.1=py_1
  - expat=2.2.5=h6de7cb9_1003
  - fastani=1.3=h41c106a_0
  - fasttree=2.1.10=h1de35cc_3
  - fontconfig=2.13.1=h1027ab8_1000
  - freetype=2.10.1=h8da9a1a_0
  - fribidi=1.0.9=h0b31af3_0
  - gettext=0.19.8.1=h46ab8bc_1002
  - gfortran_osx-64=4.8.5=h22b1bf0_8
  - giflib=5.2.1=h0b31af3_2
  - gitdb=4.0.2=py_0
  - gitpython=3.1.0=py_0
  - glib=2.58.3=h9d45998_1002
  - graphite2=1.3.13=h2098e52_1000
  - graphviz=2.40.1=h69955ae_1
  - gsl=2.4=ha2d443c_1006
  - harfbuzz=2.4.0=h92b87b8_1
  - hdf5-1105=1.10.5=0
  - hmmer=3.3=h6de7cb9_0
  - htslib=1.9=h3a161e8_7
  - icu=58.2=h0a44026_1000
  - idna=2.9=py_1
  - illumina-utils=2.7=py_0
  - importlib-metadata=1.6.0=py36h9f0ad1d_0
  - importlib_metadata=1.6.0=0
  - importlib_resources=1.4.0=py36h9f0ad1d_0
  - infernal=1.1.2=h1de35cc_2
  - ipython_genutils=0.2.0=py_1
  - iqtree=1.6.12=h2dec4b4_0
  - jaraco.classes=3.1.0=py_0
  - jaraco.collections=3.0.0=py_0
  - jaraco.functools=3.0.0=py_0
  - jaraco.text=3.2.0=py36_0
  - joblib=0.14.1=py_0
  - jpeg=9c=h1de35cc_1001
  - jsonschema=3.2.0=py36h9f0ad1d_1
  - jupyter_core=4.6.3=py36h9f0ad1d_1
  - kiwisolver=1.1.0=py36h770b8ee_0
  - krb5=1.16.4=hddcf347_0
  - ld64=274.2=1
  - libblas=3.8.0=14_openblas
  - libcblas=3.8.0=14_openblas
  - libcurl=7.68.0=h709d2b2_0
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libdb=6.1.26=0
  - libdeflate=1.0=h1de35cc_1
  - libedit=3.1.20181209=hb402a30_0
  - libfaketime=0.9.8=h0b31af3_0
  - libffi=3.2.1=h475c297_4
  - libgcc=4.8.5=hdbeacc1_10
  - libgd=2.2.5=h8cbe2a3_1005
  - libgfortran=3.0.1=0
  - libiconv=1.15=h0b31af3_1006
  - libidn11=1.34=h112b980_0
  - liblapack=3.8.0=14_openblas
  - libopenblas=0.3.7=hd44dcd8_1
  - libpng=1.6.37=hbbe82c9_1
  - libssh2=1.8.2=hcdc9a53_2
  - libtiff=4.1.0=hcb84e12_0
  - libwebp=1.0.2=hd3bf737_5
  - libxcb=1.13=h1de35cc_1002
  - libxml2=2.9.9=hd80cff7_2
  - libxslt=1.1.32=h1e79283_1003
  - llvm=4.0.1=1
  - llvm-lto-tapi=4.0.1=1
  - llvm-openmp=8.0.1=h770b8ee_0
  - llvmlite=0.29.0=py36h3fea490_1
  - lxml=4.4.1=py36h08abf6f_0
  - lz4=3.0.2=py36hb3a0f92_1
  - lz4-c=1.8.3=h6de7cb9_1001
  - mafft=7.467=h0b31af3_0
  - make=4.3=h0b31af3_0
  - matplotlib=3.1.1=py36_1
  - matplotlib-base=3.1.1=py36h3a684a6_1
  - mcl=14.137=pl526h01d97ff_5
  - megahit=1.2.9=hfbae3c0_0
  - minced=0.4.2=0
  - mistune=0.8.4=py36h0b31af3_1000
  - mlst=2.9=h01d97ff_2
  - modeller=9.24=py36_1
  - more-itertools=8.2.0=py_0
  - mummer=3.23=h6de7cb9_11
  - muscle=3.8.1551=h770b8ee_5
  - nbformat=5.0.4=py_0
  - ncbi-genome-download=0.2.10=py36_0
  - ncurses=6.1=h0a44026_1
  - numba=0.45.1=py36h86efe34_0
  - numpy=1.18.1=py36hdc5ca10_1
  - openjdk=11.0.1=hbbe82c9_1018
  - openmp=8.0.1=0
  - openssl=1.1.1g=h0b31af3_0
  - paml=4.9=h01d97ff_5
  - pandas=0.25.1=py36h86efe34_0
  - pandoc=2.9.2=0
  - pango=1.42.4=haa940fe_4
  - parallel=20200522=0
  - patsy=0.5.1=py_0
  - pcre=8.43=h0a44026_0
  - perl=5.26.2=haec8ef5_1006
  - perl-aceperl=1.92=pl526_2
  - perl-algorithm-diff=1.1903=pl526_2
  - perl-algorithm-munkres=0.08=pl526_1
  - perl-apache-test=1.40=pl526_1
  - perl-app-cpanminus=1.7044=pl526_1
  - perl-appconfig=1.71=pl526_1
  - perl-archive-tar=2.32=pl526_0
  - perl-array-compare=3.0.1=pl526_1
  - perl-array-utils=0.5=pl526_2
  - perl-autoloader=5.74=pl526_2
  - perl-base=2.23=pl526_1
  - perl-bio-asn1-entrezgene=1.73=pl526_1
  - perl-bio-coordinate=1.007001=pl526_1
  - perl-bio-featureio=1.6.905=pl526_2
  - perl-bio-phylo=0.58=pl526_2
  - perl-bio-samtools=1.43=pl526h1341992_1
  - perl-bio-tools-phylo-paml=1.7.3=pl526_1
  - perl-bio-tools-run-alignment-clustalw=1.7.4=pl526_1
  - perl-bioperl=1.7.2=pl526_10
  - perl-bioperl-core=1.007002=pl526_2
  - perl-bioperl-run=1.007002=pl526_4
  - perl-business-isbn=3.004=pl526_0
  - perl-business-isbn-data=20140910.003=pl526_0
  - perl-cache-cache=1.08=pl526_0
  - perl-capture-tiny=0.48=pl526_0
  - perl-carp=1.38=pl526_3
  - perl-cgi=4.44=pl526h1de35cc_1
  - perl-class-data-inheritable=0.08=pl526_1
  - perl-class-inspector=1.34=pl526_0
  - perl-class-load=0.25=pl526_0
  - perl-class-load-xs=0.10=pl526h04f5b5a_2
  - perl-class-method-modifiers=2.12=pl526_0
  - perl-clone=0.42=pl526h01d97ff_0
  - perl-common-sense=3.74=pl526_2
  - perl-compress-raw-bzip2=2.087=pl526h6de7cb9_0
  - perl-compress-raw-zlib=2.087=pl526h770b8ee_0
  - perl-constant=1.33=pl526_1
  - perl-convert-binary-c=0.78=pl526h04f5b5a_3
  - perl-convert-binhex=1.125=pl526_1
  - perl-crypt-rc4=2.02=pl526_1
  - perl-data-dumper=2.173=pl526_0
  - perl-data-optlist=0.110=pl526_2
  - perl-data-stag=0.14=pl526_1
  - perl-date-format=2.30=pl526_2
  - perl-db-file=1.852=pl526h1de35cc_0
  - perl-dbd-sqlite=1.64=pl526h01d97ff_0
  - perl-dbi=1.642=pl526_0
  - perl-devel-globaldestruction=0.14=pl526_0
  - perl-devel-overloadinfo=0.005=pl526_0
  - perl-devel-stacktrace=2.04=pl526_0
  - perl-digest-hmac=1.03=pl526_3
  - perl-digest-md5=2.55=pl526_0
  - perl-digest-md5-file=0.08=pl526_2
  - perl-digest-perl-md5=1.9=pl526_1
  - perl-digest-sha1=2.13=pl526h04f5b5a_1
  - perl-dist-checkconflicts=0.11=pl526_2
  - perl-dynaloader=1.25=pl526_1
  - perl-email-date-format=1.005=pl526_2
  - perl-encode=2.88=pl526_1
  - perl-encode-locale=1.05=pl526_6
  - perl-env-path=0.19=pl526_2
  - perl-error=0.17027=pl526_1
  - perl-eval-closure=0.14=pl526h04f5b5a_4
  - perl-exception-class=1.44=pl526_0
  - perl-exporter=5.72=pl526_1
  - perl-exporter-tiny=1.002001=pl526_0
  - perl-extutils-makemaker=7.36=pl526_1
  - perl-file-find-rule=0.34=pl526_5
  - perl-file-grep=0.02=pl526_3
  - perl-file-listing=6.04=pl526_1
  - perl-file-path=2.16=pl526_0
  - perl-file-slurp-tiny=0.004=pl526_1
  - perl-file-slurper=0.012=pl526_0
  - perl-file-sort=1.01=pl526_2
  - perl-file-temp=0.2304=pl526_2
  - perl-file-which=1.23=pl526_0
  - perl-font-afm=1.20=pl526_2
  - perl-font-ttf=1.06=pl526_0
  - perl-gd=2.71=pl526h5c9b4e4_0
  - perl-getopt-long=2.50=pl526_1
  - perl-graph=0.9704=pl526_1
  - perl-graph-readwrite=2.09=pl526_2
  - perl-graphviz=2.24=pl526h734ff71_0
  - perl-html-element-extended=1.18=pl526_1
  - perl-html-entities-numbered=0.04=pl526_1
  - perl-html-formatter=2.16=pl526_0
  - perl-html-parser=3.72=pl526h04f5b5a_5
  - perl-html-tableextract=2.13=pl526_2
  - perl-html-tagset=3.20=pl526_3
  - perl-html-tidy=1.60=pl526_0
  - perl-html-tree=5.07=pl526_1
  - perl-html-treebuilder-xpath=0.14=pl526_1
  - perl-http-cookies=6.04=pl526_0
  - perl-http-daemon=6.01=pl526_1
  - perl-http-date=6.02=pl526_3
  - perl-http-message=6.18=pl526_0
  - perl-http-negotiate=6.01=pl526_3
  - perl-image-info=1.38=pl526_1
  - perl-image-size=3.300=pl526_2
  - perl-io-compress=2.087=pl526h6de7cb9_0
  - perl-io-html=1.001=pl526_2
  - perl-io-sessiondata=1.03=pl526_1
  - perl-io-socket-ssl=2.066=pl526_0
  - perl-io-string=1.08=pl526_3
  - perl-io-stringy=2.111=pl526_1
  - perl-io-tty=1.12=pl526_1
  - perl-io-zlib=1.10=pl526_2
  - perl-ipc-run=20180523.0=pl526_0
  - perl-ipc-sharelite=0.17=pl526h04f5b5a_1
  - perl-jcode=2.07=pl526_2
  - perl-json=4.02=pl526_0
  - perl-json-xs=2.34=pl526h04f5b5a_3
  - perl-lib=0.63=pl526_1
  - perl-libwww-perl=6.39=pl526_0
  - perl-libxml-perl=0.08=pl526_2
  - perl-list-moreutils=0.428=pl526_1
  - perl-list-moreutils-xs=0.428=pl526_0
  - perl-log-log4perl=1.49=pl526_0
  - perl-lwp-mediatypes=6.04=pl526_0
  - perl-lwp-protocol-https=6.07=pl526_4
  - perl-lwp-simple=6.15=pl526h470a237_4
  - perl-mailtools=2.21=pl526_0
  - perl-math-cdf=0.1=pl526h1de35cc_5
  - perl-math-derivative=1.01=pl526_0
  - perl-math-random=0.72=pl526h1de35cc_2
  - perl-math-spline=0.02=pl526_2
  - perl-mime-base64=3.15=pl526_1
  - perl-mime-lite=3.030=pl526_1
  - perl-mime-tools=5.508=pl526_1
  - perl-mime-types=2.17=pl526_0
  - perl-mldbm=2.05=pl526_1
  - perl-module-implementation=0.09=pl526_2
  - perl-module-runtime=0.016=pl526_1
  - perl-module-runtime-conflicts=0.003=pl526_0
  - perl-moo=2.001000=pl526_2
  - perl-moose=2.2011=pl526h0a44026_1
  - perl-mozilla-ca=20180117=pl526_1
  - perl-mro-compat=0.13=pl526_0
  - perl-net-http=6.19=pl526_0
  - perl-net-ssleay=1.88=pl526hb1dc21d_0
  - perl-ntlm=1.09=pl526_4
  - perl-number-compare=0.03=pl526_2
  - perl-ole-storage_lite=0.19=pl526_3
  - perl-package-deprecationmanager=0.17=pl526_0
  - perl-package-stash=0.38=pl526h0a44026_1
  - perl-package-stash-xs=0.28=pl526h0a44026_1
  - perl-params-util=1.07=pl526h04f5b5a_4
  - perl-parent=0.236=pl526_1
  - perl-parse-recdescent=1.967015=pl526_0
  - perl-parse-yapp=1.21=pl526_0
  - perl-pathtools=3.75=pl526h1de35cc_1
  - perl-pdf-api2=2.035=pl526_0
  - perl-perlio-utf8_strict=0.007=pl526h04f5b5a_1
  - perl-pod-escapes=1.07=pl526_1
  - perl-pod-usage=1.69=pl526_1
  - perl-postscript=0.06=pl526_2
  - perl-role-tiny=2.000008=pl526_0
  - perl-scalar-list-utils=1.52=pl526h01d97ff_0
  - perl-set-scalar=1.29=pl526_2
  - perl-soap-lite=1.19=pl526_1
  - perl-socket=2.027=pl526_1
  - perl-sort-naturally=1.03=pl526_2
  - perl-spreadsheet-parseexcel=0.65=pl526_2
  - perl-spreadsheet-writeexcel=2.40=pl526_2
  - perl-statistics-descriptive=3.0702=pl526_0
  - perl-storable=3.15=pl526h1de35cc_0
  - perl-sub-exporter=0.987=pl526_2
  - perl-sub-exporter-progressive=0.001013=pl526_0
  - perl-sub-identify=0.14=pl526h1de35cc_0
  - perl-sub-install=0.928=pl526_2
  - perl-sub-name=0.21=pl526_1
  - perl-sub-uplevel=0.2800=pl526h1de35cc_2
  - perl-svg=2.84=pl526_0
  - perl-svg-graph=0.02=pl526_3
  - perl-task-weaken=1.06=pl526_0
  - perl-template-toolkit=2.26=pl526_1
  - perl-test=1.26=pl526_1
  - perl-test-builder-tester=1.23_002=pl526_1
  - perl-test-deep=1.128=pl526_1
  - perl-test-differences=0.67=pl526_0
  - perl-test-exception=0.43=pl526_2
  - perl-test-files=0.14=pl526_2
  - perl-test-harness=3.42=pl526_0
  - perl-test-leaktrace=0.16=pl526h1de35cc_2
  - perl-test-most=0.35=pl526_0
  - perl-test-output=1.031=pl526_0
  - perl-test-requiresinternet=0.05=pl526_0
  - perl-test-warn=0.36=pl526_1
  - perl-text-csv=2.00=pl526_0
  - perl-text-diff=1.45=pl526_0
  - perl-text-glob=0.11=pl526_1
  - perl-threaded=5.26.0=0
  - perl-tie-ixhash=1.23=pl526_2
  - perl-time-hires=1.9760=pl526h1de35cc_1
  - perl-time-local=1.28=pl526_1
  - perl-timedate=2.30=pl526_1
  - perl-tree-dag_node=1.31=pl526_0
  - perl-try-tiny=0.30=pl526_1
  - perl-type-tiny=1.004004=pl526_0
  - perl-types-serialiser=1.0=pl526_2
  - perl-unicode-map=0.112=pl526h04f5b5a_3
  - perl-uri=1.76=pl526_0
  - perl-www-robotrules=6.02=pl526_3
  - perl-xml-dom=1.46=pl526_0
  - perl-xml-dom-xpath=0.14=pl526_1
  - perl-xml-filter-buffertext=1.01=pl526_2
  - perl-xml-libxml=2.0132=pl526h08abf6f_1
  - perl-xml-libxslt=1.94=pl526_1
  - perl-xml-namespacesupport=1.12=pl526_0
  - perl-xml-parser=2.44_01=pl526h4c9d1cc_1002
  - perl-xml-regexp=0.04=pl526_2
  - perl-xml-sax=1.02=pl526_0
  - perl-xml-sax-base=1.09=pl526_0
  - perl-xml-sax-expat=0.51=pl526_3
  - perl-xml-sax-writer=0.57=pl526_0
  - perl-xml-simple=2.25=pl526_1
  - perl-xml-twig=3.52=pl526_2
  - perl-xml-writer=0.625=pl526_2
  - perl-xml-xpath=1.44=pl526_0
  - perl-xml-xpathengine=0.14=pl526_2
  - perl-xsloader=0.24=pl526_0
  - perl-yaml=1.29=pl526_0
  - pixman=0.38.0=h01d97ff_1003
  - portend=2.6=pyh9f0ad1d_0
  - prank=v.170427=h04f5b5a_2
  - prodigal=2.6.3=h01d97ff_2
  - prokka=1.14.6=pl526_0
  - psutil=5.4.3=py36_0
  - pthread-stubs=0.4=h1de35cc_1001
  - pyani=0.2.10=py_0
  - pycparser=2.20=py_0
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.6=py_0
  - pyqt=5.9.2=py36h2a560b1_4
  - pyrsistent=0.16.0=py36h37b9a7d_0
  - pysam=0.15.3=py36h726f235_1
  - pysocks=1.7.1=py36h9f0ad1d_1
  - python=3.6.10=h359304d_0
  - python-dateutil=2.8.1=py_0
  - python-levenshtein=0.12.0=py36h0b31af3_1001
  - python_abi=3.6=1_cp36m
  - pytz=2019.3=py_0
  - pyyaml=5.3.1=py36h37b9a7d_0
  - qt=5.9.7=h93ee506_2
  - r-askpass=1.1=r35h159158b_1
  - r-assertthat=0.2.1=r35h6115d3f_1
  - r-backports=1.1.6=r35h17f1fa6_0
  - r-base=3.5.1=h539fb6c_1
  - r-base64enc=0.1_3=r35h159158b_1003
  - r-broom=0.5.5=r35h6115d3f_0
  - r-callr=3.4.3=r35h6115d3f_0
  - r-cellranger=1.1.0=r35h6115d3f_1002
  - r-cli=2.0.2=r35h6115d3f_0
  - r-clipr=0.7.0=r35h6115d3f_0
  - r-colorspace=1.4_1=r35h159158b_1
  - r-crayon=1.3.4=r35h6115d3f_1002
  - r-curl=4.3=r35h17f1fa6_0
  - r-dbi=1.1.0=r35h6115d3f_0
  - r-dbplyr=1.4.2=r35h6115d3f_1
  - r-digest=0.6.21=r35hf99fc2c_0
  - r-dplyr=0.8.3=r35hf99fc2c_3
  - r-ellipsis=0.3.0=r35h159158b_0
  - r-evaluate=0.14=r35h6115d3f_1
  - r-fansi=0.4.1=r35h17f1fa6_0
  - r-forcats=0.5.0=r35h6115d3f_0
  - r-fs=1.3.1=r35hf99fc2c_1
  - r-generics=0.0.2=r35h6115d3f_1002
  - r-getopt=1.20.3=r35_1
  - r-ggplot2=3.2.1=r35h6115d3f_0
  - r-glue=1.4.0=r35h17f1fa6_0
  - r-gtable=0.3.0=r35h6115d3f_2
  - r-haven=2.1.1=r35h16b383e_3
  - r-highr=0.8=r35h6115d3f_1
  - r-hms=0.5.3=r35h6115d3f_0
  - r-htmltools=0.3.6=r35h6de7cb9_1003
  - r-httr=1.4.1=r35h6115d3f_1
  - r-jsonlite=1.6.1=r35h17f1fa6_0
  - r-knitr=1.28=r35h6115d3f_0
  - r-labeling=0.3=r35h6115d3f_1002
  - r-lattice=0.20_41=r35h17f1fa6_0
  - r-lazyeval=0.2.2=r35h159158b_1
  - r-lifecycle=0.2.0=r35h6115d3f_0
  - r-lubridate=1.7.4=r35hf99fc2c_1002
  - r-magrittr=1.5=r35h6115d3f_1002
  - r-markdown=1.1=r35h159158b_0
  - r-mass=7.3_51.5=r35h17f1fa6_0
  - r-matrix=1.2_18=r35h26f5615_2
  - r-mgcv=1.8_28=r35h159158b_1
  - r-mime=0.9=r35h17f1fa6_0
  - r-modelr=0.1.6=r35h6115d3f_0
  - r-munsell=0.5.0=r35h6115d3f_1002
  - r-nlme=3.1_141=r35haf69682_1
  - r-openssl=1.4.1=r35hdb18a49_0
  - r-optparse=1.6.4=r35h6115d3f_0
  - r-pillar=1.4.3=r35h6115d3f_0
  - r-pkgconfig=2.0.3=r35h6115d3f_0
  - r-plogr=0.2.0=r35h6115d3f_1002
  - r-plyr=1.8.4=r35hf99fc2c_1003
  - r-prettyunits=1.1.1=r35h6115d3f_0
  - r-processx=3.4.2=r35h17f1fa6_0
  - r-progress=1.2.2=r35h6115d3f_1
  - r-ps=1.3.2=r35h17f1fa6_0
  - r-purrr=0.3.3=r35h17f1fa6_0
  - r-r6=2.4.1=r35h6115d3f_0
  - r-rcolorbrewer=1.1_2=r35h6115d3f_1002
  - r-rcpp=1.0.2=r35hf99fc2c_0
  - r-readr=1.3.1=r35hf99fc2c_1002
  - r-readxl=1.3.1=r35hf99fc2c_2
  - r-rematch=1.0.1=r35h6115d3f_1002
  - r-reprex=0.3.0=r35h6115d3f_1
  - r-reshape2=1.4.3=r35hf99fc2c_1004
  - r-rlang=0.4.5=r35h17f1fa6_0
  - r-rmarkdown=2.1=r35h6115d3f_0
  - r-rstudioapi=0.11=r35h6115d3f_0
  - r-rvest=0.3.5=r35h6115d3f_0
  - r-scales=1.0.0=r35hf99fc2c_1002
  - r-selectr=0.4_2=r35h6115d3f_0
  - r-stringi=1.4.3=r35hf99fc2c_2
  - r-stringr=1.4.0=r35h6115d3f_1
  - r-sys=3.3=r35h159158b_0
  - r-tibble=3.0.0=r35h17f1fa6_0
  - r-tidyr=1.0.0=r35hf99fc2c_0
  - r-tidyselect=1.0.0=r35h6115d3f_0
  - r-tidyverse=1.2.1=r351hf348343_0
  - r-tinytex=0.21=r35h6115d3f_0
  - r-utf8=1.1.4=r35h159158b_1001
  - r-vctrs=0.2.4=r35h17f1fa6_0
  - r-viridislite=0.3.0=r35h6115d3f_1002
  - r-whisker=0.4=r35h6115d3f_0
  - r-withr=2.1.2=r35h6115d3f_1001
  - r-xfun=0.12=r35h6115d3f_0
  - r-xml2=1.2.2=r35hf99fc2c_0
  - r-yaml=2.2.1=r35h17f1fa6_0
  - r-zeallot=0.1.0=r35h6115d3f_1001
  - ratelimiter=1.2.0=py36_1000
  - readline=7.0=h1de35cc_5
  - repoze.lru=0.7=py_0
  - requests=2.23.0=pyh8c360ce_2
  - roary=3.13.0=pl526h01d97ff_0
  - routes=2.4.1=py36_0
  - samtools=1.9=h8aa4d43_12
  - scikit-learn=0.21.3=py36hd4ffd6c_0
  - scipy=1.3.1=py36hab3da7d_2
  - seaborn=0.10.0=py_1
  - setuptools=46.1.3=py36_0
  - simplejson=3.17.0=py36h0b31af3_0
  - sip=4.19.8=py36h0a44026_1000
  - six=1.14.0=py_1
  - smmap=3.0.1=py_0
  - snakemake-minimal=5.10.0=py_0
  - sqlite=3.31.1=ha441bb4_0
  - sqlparse=0.3.1=py_0
  - statsmodels=0.11.1=py36h37b9a7d_1
  - tabulate=0.8.7=pyh9f0ad1d_0
  - tbb=2019.8=h770b8ee_0
  - tbl2asn-forever=25.7.1f=0
  - tempora=3.0.0=py_0
  - tidyp=1.04=1
  - tk=8.6.8=ha441bb4_0
  - tktable=2.10=h1de35cc_0
  - toposort=1.5=py_3
  - tornado=6.0.4=py36h37b9a7d_1
  - traitlets=4.3.3=py36h9f0ad1d_1
  - trimal=1.4.1=h04f5b5a_3
  - trnascan-se=2.0.5=pl526h01d97ff_0
  - urllib3=1.25.7=py36h9f0ad1d_1
  - wget=1.20.1=h051b688_0
  - wheel=0.34.2=py36_0
  - wrapt=1.12.1=py36h37b9a7d_1
  - xorg-kbproto=1.0.7=h1de35cc_1002
  - xorg-libice=1.0.10=h01d97ff_0
  - xorg-libsm=1.2.3=h01d97ff_1000
  - xorg-libx11=1.6.9=h0b31af3_0
  - xorg-libxau=1.0.9=h1de35cc_0
  - xorg-libxdmcp=1.1.3=h01d97ff_0
  - xorg-libxext=1.3.4=h01d97ff_0
  - xorg-libxrender=0.9.10=h01d97ff_1002
  - xorg-renderproto=0.11.1=h1de35cc_1002
  - xorg-xextproto=7.3.0=h1de35cc_1002
  - xorg-xproto=7.0.31=h1de35cc_1007
  - xz=5.2.4=h1de35cc_4
  - yaml=0.2.2=h0b31af3_1
  - zc.lockfile=2.0=py_0
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h1de35cc_3
  - zstd=1.3.7=h06149cd_1001
  - pip:
    - cialign==1.0.4
    - h5py==2.10.0
    - pillow==7.1.2
    - pip==20.1
